ipld-state-dump:
  build: ./
  restart: always
  links:
    - parity
  volumes:
    - /mnt/volume-sfo2-01/data/ipfs:/var/data/ipfs
    - /mnt/volume-sfo2-01/data/sync:/var/data/sync
  environment:
    IPFS_REPO: "/var/data/ipfs"
    DB_ROOT: "/var/data/sync"
    RPC_TARGET: "http://parity:8545/"

parity:
  image: ethcore/parity:beta-release
  restart: always
  command: --rpcport "8545" --rpcaddr "all" --rpccorsdomain "*" --jsonrpc-hosts "all"
  ports:
    - "8545:8545"
